name: Create Project Issue

on: push
jobs:
  create-project-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-api-team-public/.github/actions/create-project-issue-v1@83f867a5e6f3229d2f2ab44004b38300563e0dbe
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "I am a new issue, hazaar!"
          body: "I am new issue body, also hazaar!"
